# Generated by Django 2.2.15 on 2020-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="cfghsfhsh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="fgvsgsdfsc",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="sdfastrewr",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
