# Generated by Django 2.2.15 on 2020-08-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200812_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='cfghsfhsh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='fgvsgsdfsc',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='sdfastrewr',
        ),
    ]
