# Generated by Django 2.2.15 on 2020-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200812_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hffhgfjghfjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgjhgjhg', models.BigIntegerField()),
            ],
        ),
    ]
